/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/templates/**/*.html",
    "./app/static/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf8fe",
        "surface-dim": "#dbd9df",
        "surface-bright": "#fbf8fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2f9",
        "surface-container": "#efedf3",
        "surface-container-high": "#eae7ed",
        "surface-container-highest": "#e4e1e7",
        "on-surface": "#1b1b20",
        "on-surface-variant": "#454650",
        "inverse-surface": "#303035",
        "inverse-on-surface": "#f2f0f6",
        "outline": "#767681",
        "outline-variant": "#c6c5d1",
        "surface-tint": "#4f5a9a",
        "primary": "#131f5d",
        "on-primary": "#ffffff",
        "primary-container": "#2b3674",
        "on-primary-container": "#97a1e7",
        "inverse-primary": "#bac3ff",
        "secondary": "#2e00c8",
        "on-secondary": "#ffffff",
        "secondary-container": "#4317ff",
        "on-secondary-container": "#c8c3ff",
        "tertiary": "#3c1e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5b3100",
        "on-tertiary-container": "#d69960",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dee0ff",
        "primary-fixed-dim": "#bac3ff",
        "on-primary-fixed": "#061353",
        "on-primary-fixed-variant": "#374280",
        "secondary-fixed": "#e3dfff",
        "secondary-fixed-dim": "#c5c0ff",
        "on-secondary-fixed": "#130067",
        "on-secondary-fixed-variant": "#3600e1",
        "tertiary-fixed": "#ffdcc0",
        "tertiary-fixed-dim": "#fbb97d",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#693c0a",
        "background": "#fbf8fe",
        "on-background": "#1b1b20",
        "surface-variant": "#e4e1e7",
        "deep-indigo": "#1B2559",
        "slate-gray": "#707EAE",
        "glass-white": "rgba(255, 255, 255, 0.8)",
        "success-teal": "#05CD99",
        "privacy-blue": "#E9EDF7",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-display": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
